// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbN3Ebuu1mq938UQ907prgDuZ_i_qZwMs',
    appId: '1:526623223297:web:5e8048920dc1d727a45a00',
    messagingSenderId: '526623223297',
    projectId: 'bloodbridge-1a391',
    authDomain: 'bloodbridge-1a391.firebaseapp.com',
    storageBucket: 'bloodbridge-1a391.firebasestorage.app', 
    databaseURL: "https://bloodbridge-1a391-default-rtdb.firebaseio.com/"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyWqFngfeR003C06OuK_u5AMhk4Ut2sp0',
    appId: '1:526623223297:android:8922b4b54c6d7f24a45a00',
    messagingSenderId: '526623223297',
    projectId: 'bloodbridge-1a391',
    storageBucket: 'bloodbridge-1a391.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtrEwy_0Eo50poC7Veyny8cNPXhGOQJpY',
    appId: '1:526623223297:ios:06d6f2e7c6d6a663a45a00',
    messagingSenderId: '526623223297',
    projectId: 'bloodbridge-1a391',
    storageBucket: 'bloodbridge-1a391.firebasestorage.app',
    iosBundleId: 'com.example.bloodbridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtrEwy_0Eo50poC7Veyny8cNPXhGOQJpY',
    appId: '1:526623223297:ios:06d6f2e7c6d6a663a45a00',
    messagingSenderId: '526623223297',
    projectId: 'bloodbridge-1a391',
    storageBucket: 'bloodbridge-1a391.firebasestorage.app',
    iosBundleId: 'com.example.bloodbridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbN3Ebuu1mq938UQ907prgDuZ_i_qZwMs',
    appId: '1:526623223297:web:ba834086f4617406a45a00',
    messagingSenderId: '526623223297',
    projectId: 'bloodbridge-1a391',
    authDomain: 'bloodbridge-1a391.firebaseapp.com',
    storageBucket: 'bloodbridge-1a391.firebasestorage.app',
  );
}
